import type { Metadata } from "next";
import { Pacifico } from "next/font/google"; // Geistフォントのimportを削除
import "./globals.css";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
});

// Geistフォントの定義を削除

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${pacifico.variable} antialiased`} // 使用するフォントをPacificoのみに修正
      >
        {children}
      </body>
    </html>
  );
}
